site_name: Verbose Guacamole
repo_url: https://github.com/benjaminbhollon/verbose-guacamole-docs
copyright: Verbose Guacamole is licensed under GPL-3.0
theme:
  name: readthedocs
markdown_extensions:
    - toc:
        permalink: "#"
edit_uri: edit/main/docs/
site_description: The documentation for Verbose Guacamole, the Markdown and Git powered novel editor.
site_author: Benjamin Hollon and the Verbose Guacamole contributors
